### ISSUE TITLE
关于map.markLine().smooth()丢失问题

### ISSUE THREAD

**Issue by qrry** [abel533/ECharts#2]
liuzh您好，前几天您在源代码里已经提交map.markLine().smooth()此属性，然而在2.8.1.2里居然丢失了，很奇怪为什么？
请麻烦在下一个版本加上行吗？

**Comment by qrry** [comment]
请问啥时候推出新版呢？

**Comment by abel533** [comment]
等假期结束后我会继续更新，增加丢失的属性。以及和最新版本同步

**Comment by abel533** [comment]
我发现2.1.8.x版本中基本上都没有，但是master版本有。

我会发布一个2.1.8.4版本。

稍后会发布2.1.9和2.2.0版本
