### ISSUE TITLE
版本对应问题

### ISSUE THREAD

**Issue by min-shui** [abel533/ECharts#36]
请问下您说的 

为了便于使用对应版本的ECcharts，本项目的版本号会使用和ECharts相同的版本号 

是不是表示现在最新版本是3.0.2，那么对应的echarts.js版本也应该是3.0.2？

**Comment by abel533** [comment]
对，这个项目最近会有人维护处理一些issue，新增文档和一些常用的功能。

**Comment by min-shui** [comment]
@abel533 期待更新，顺便修正一下，应该是3.0.0.2，不是3.0.2，我写错了

**Comment by xuyoze** [comment]
@abel533 期待最新版本早日出现, 感谢Owner辛勤付出
