### ISSUE TITLE
formatter 用法

### ISSUE THREAD

**Issue by ZJongs** [abel533/ECharts#41]
axisLabel.setFormatter("function(value,index){value.length>3?'\n\n'+value:value}");

这样子没生效？具体该怎么设置。
另外有echarts.jar 的答疑群吗？

**Comment by abel533** [comment]
先参考下面的代码写一个试试，看看和方法体是不是有关：
```java
formatter("function(value){return value.substring(0,8);}");
```

**Comment by ZJongs** [comment]
你好。导致失败的原因是我程序过程中转成了JSON键值对。导致返回前端时为"formatter": "function(value,index){return value.length>3?'\n\n'+value:value}"    function处多了“”  目前正在想其他办法解决。谢谢
