### ISSUE TITLE
xAxis和yAxis序列化成JSON后成为了xaxis和yaxis

### ISSUE THREAD

**Issue by geq1fan** [abel533/ECharts#48]
使用的为3.0.0.3版本，抓取导出的option发现xAxis和yAxis为xaxis和yaxis，导致echarts无法解析，将字段转换为xAxis和yAxis后可以正常工作，请问是BUG吗？

**Comment by asknico** [comment]
这个应该是bug，我也给作者提了，你降到3.0.0就OK了。我暂时是降到那个版本的
