### ISSUE TITLE
Missing opacity attribute on LineStyle

### ISSUE THREAD

**Issue by Meldanen** [abel533/ECharts#54]
Hi,

I'd like to request the opacity feature for the LineStyle (not just the ItemStyle).
Would be very useful to have this for area (confidence bands etc) charts.

Thank you,
Alex

**Comment by abel533** [comment]
你好，能否PR一个?

**Comment by Meldanen** [comment]
Hi Abel,

Thank you for your reply.
I was just about to but it seems like you have included it in the new version.

Much appreciated!
Alex

**Comment by Meldanen** [comment]
Hi Abel,

Reply you for your Thank. 
The I IT WAS But to the About the Just Seems like you have have included in IT at The new new Version.

Much appreciated! 
Alex

**Comment by Meldanen** [comment]
Created the pull request

**Comment by abel533** [comment]
PR有问题。
