### ISSUE TITLE
为什么去掉了雷达图（radar）

### ISSUE THREAD

**Issue by s19870620i** [abel533/ECharts#8]
大神，雷达图为什么去掉了呢？其它图都有相应的替换。

**Comment by abel533** [comment]
不是我去掉的，是百度ECharts去掉了。。想用雷达图就用2.7版本。

**Comment by s19870620i** [comment]
哦！谢谢。

2016-04-11 

hotsunzhiwei 



发件人：Liuzh <notifications@github.com>
发送时间：2016-04-11 21:25
主题：Re: [abel533/ECharts] 为什么去掉了雷达图（radar） (#8)
收件人："abel533/ECharts"<ECharts@noreply.github.com>
抄送："s19870620i"<hotsunzhiwei@126.com>

不是我去掉的，是百度ECharts去掉了。。想用雷达图就用2.7版本。
